Feat: set-wall support standalone images

diff --git a/scripts/set-wall b/scripts/set-wall
--- a/scripts/set-wall
+++ b/scripts/set-wall
@@ -1,10 +1,12 @@
 #!/bin/sh
 if [ "$1" = "-h" ]; then
-  echo "Usage: $0 [IMAGE_DIR]"
+  echo "Usage: $0 [Image or Directory]"
   exit 1
 fi
 
-image_dir=${1:-~/Backgrounds/safe_for_powerpoint}
+arg=${1:-~/Backgrounds/safe_for_powerpoint}
+
+# Check if swww exists
 if ! swww -V &>/dev/null; then
   echo "Error: swww not found" >&2
   exit 1
@@ -12,5 +14,18 @@ fi
 if ! swww query &>/dev/null; then
   swww init
 fi
-image=$(ls "$image_dir" | shuf -n 1)
-swww img "$image_dir/$image" --transition-type wipe
+
+
+if [ -d "$arg" ]; then
+	# Directory
+	image=$(ls "$arg" | shuf -n 1)
+	image="$arg/$image"
+elif [ -f "$arg" ]; then
+	# Image
+	image="$arg"
+else
+	# Neither
+	echo "Error: Argument is not image or directory" >&2
+	exit 1
+fi
+swww img "$image" --transition-type wipe
